### ISSUE TITLE
UTF characters not displayed correctly in Tableau

### ISSUE THREAD

**Issue by griguolcomerranas** [Altinity/clickhouse-tableau-connector-odbc#20]
UTF characters are correct in the database but they do not display correctly in Tableau.

For instance the string "Baden-Württemberg" in the database is showing in Tableau as "Baden-WÃ¼rttemberg"
When using directly the ODBC Driver with a defined DSN then it works fine but when using the taco file it doesn't work.

Am I missing something? Any additional configuration needed?

I am using the latest Unicode ODBC connector,  clichouse 21.12.3.32 and Tableau Desktop 2021.2.7

Thanks a lot for your great work!

**Comment by dima-altinity** [comment]
Hi @griguolcomerranas 

it was done intentionally because unicode odbc driver is failing in some situations and doesnt pass couple Tableau tests.
There is build (Taco file) published in releases section which use UNICODE.
https://github.com/Altinity/clickhouse-tableau-connector-odbc/releases/tag/v1.0.0-odbc-unicode
Download it from there and install.

**Comment by griguolcomerranas** [comment]
Hi,

Please double check the file. The one I am using is actually the unicode release you are pointing (v1.0.0-odbc-unicode), and it is NOT using the unicode driver.

Look at the connectionResolver file:

`<driver-name type='exact'>ClickHouse ODBC Driver (ANSI)</driver-name>`
