### ISSUE TITLE
Unicode TACO file is not Unicode - ANSI is in the source code and TACO file

### ISSUE THREAD

**Issue by kuntzi** [Altinity/clickhouse-tableau-connector-odbc#22]
@dima-altinity
I'm raising this issue third time! Please pay attention to the wording!
Previous Issue 1 - (https://github.com/Altinity/clickhouse-tableau-connector-odbc/issues/18)
Previous Issue 2 - https://github.com/Altinity/clickhouse-tableau-connector-odbc/issues/20

And issue still exists.

You mentioned that proper Unicode TACO file is here: 
https://github.com/Altinity/clickhouse-tableau-connector-odbc/releases/tag/v1.0.0-odbc-unicode

But when I open both source and TACO file from that link (please open files and recheck!) - I see ANSI version of the driver, not Unicode! It's only named "Unicode", but it's not Unicode, it's ANSI.

Please, compile Unicode version of TACO file and republish it.
We have difficulties with Cyrillic characters.

**Comment by dima-altinity** [comment]
@kuntzi 
yes, sorry, attached wrong file during publishing release.
In sources it still remain as ANSI because there is problem in ODBC driver with some datasets if you use Unicode version.
You could see this problem if you try to connect to CH playground and open any table in Tableau. 
https://clickhouse.com/docs/en/getting-started/playground/

It needs more time to investigate root cause and I'm really busy now.
I just published proper TACO file ( unicode version ) in the same release.
Could you try and confirm if it works for you?
https://github.com/Altinity/clickhouse-tableau-connector-odbc/releases/tag/v1.0.0-odbc-unicode

**Comment by kuntzi** [comment]
@dima-altinity Thanks a lot! It works now.
